# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shipshape < Formula
  desc "Golang CLI tool to run checks/audits on your systems"
  homepage "https://github.com/salsadigitalauorg/shipshape"
  version "1.0.0-alpha.1.0"

  on_macos do
    on_intel do
      url "https://github.com/salsadigitalauorg/shipshape/releases/download/v1.0.0-alpha.1.0/shipshape-Darwin-x86_64.tar.gz"
      sha256 "9b4f7679bf2aa42f60dde0e3fa236b10fc7ea060258168dfc7ec7183fbb7ae07"

      def install
        bin.install "shipshape"
      end
    end
    on_arm do
      url "https://github.com/salsadigitalauorg/shipshape/releases/download/v1.0.0-alpha.1.0/shipshape-Darwin-aarch64.tar.gz"
      sha256 "4c02c2e0813dd3e806d51c575d10f629dcdb5680e38df0d2a84884802099602e"

      def install
        bin.install "shipshape"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/salsadigitalauorg/shipshape/releases/download/v1.0.0-alpha.1.0/shipshape-Linux-x86_64.tar.gz"
        sha256 "0624a81427450412a1daf1e3357f051843d90fd92d45f29660aff83dcdf9a61a"

        def install
          bin.install "shipshape"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/salsadigitalauorg/shipshape/releases/download/v1.0.0-alpha.1.0/shipshape-Linux-aarch64.tar.gz"
        sha256 "e9bb806bc5d47ef098fd9d964a6240153c573ddf0a2fcc6e8ac2d439b07f4f25"

        def install
          bin.install "shipshape"
        end
      end
    end
  end

  test do
    system "#{bin}/shipshape version"
  end
end
